[build]
  publish = "."
  
[[redirects]]
  from = "/"
  to = "/Original%20HTML.html"
  status = 200

[[redirects]]
  from = "/diagram"
  to = "/Solar_Array_Diagram_Updated.html"
  status = 200

[[redirects]]
  from = "/blog"
  to = "/blog.html"
  status = 200